<a href="https://colab.research.google.com/github/charmi-devisetty/B5_PFDS_CLASSROOM/blob/main/Numpy_classroom.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
b=np.array([[1,2],[3,4]])
print(b)

[[1 2]
 [3 4]]


In [ ]:
c = np.zeros((2, 2))
print(c)

[[0. 0.]
 [0. 0.]]


In [ ]:
d=np.ones((3,3))
print(d)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
range_arr=np.arange(0,10,2)
print(range_arr)

[0 2 4 6 8]


In [ ]:
rand_arr=np.random.rand(3,3)
print(rand_arr)

[[0.24423299 0.67896124 0.64968243]
 [0.34437849 0.06796526 0.54682424]
 [0.73714374 0.80387057 0.62965917]]


In [ ]:
a=np.array([[1,2,3],[4,5,6]])
print(a.shape)
print(a.ndim)
print(a.dtype)
print(a.size)
print(a.itemsize)

(2, 3)
2
int64
6
8


In [ ]:
arr=np.array([10,20,30,40,50])
print("first ele",arr[0])
print("second ele",arr[1])
print("last ele",arr[-1])
print("slice[1:4]:",arr[1:4])
print("every second ele",arr[::2])

first ele 10
second ele 20
last ele 50
slice[1:4]: [20 30 40]
every second ele [10 30 50]


In [ ]:
c=np.array([[1,2,3,4,5]])
print(c)

[[1 2 3 4 5]]


In [ ]:
d=np.array([[1,2,3],[4,5,6]])
e=np.array([[3,4,5],[2,1,7]])
print(d)
print(e)


[[1 2 3]
 [4 5 6]]
[[3 4 5]
 [2 1 7]]


In [ ]:
print(d+e)
print(d-e)
print(d*e)
print(d/e)
print(d**2)

[[ 4  6  8]
 [ 6  6 13]]
[[-2 -2 -2]
 [ 2  4 -1]]
[[ 3  8 15]
 [ 8  5 42]]
[[0.33333333 0.5        0.6       ]
 [2.         5.         0.85714286]]
[[ 1  4  9]
 [16 25 36]]


In [ ]:
f=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(f)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [22]:
arr=np.array([[1,1,1],[2,3,4]])
print("sum:",np.sum(arr))
print("Max:",np.max(arr))
print("min:",np.min(arr))
print("Mean:",np.mean(arr))
print("Standard deviation:",np.std(arr))
print("Sum along axis 0:",np.sum(arr,axis=0))

sum: 12
Max: 4
min: 1
Mean: 2.0
Standard deviation: 1.1547005383792515
Sum along axis 0: [3 4 5]


In [ ]:
a=np.array([1,2,3])
b=5
print(a+b)

[6 7 8]


In [ ]:
c=np.array([[1,2,3],[4,5,6]])
d=np.array([1,2,3])
print(c+d)

[[2 4 6]
 [5 7 9]]
